name: bp-integration
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - anndata=0.7.6
  - bbknn=1.5.1
  - hdf5=1.12.1
  - ipykernel=6.4.1
  - ipython=7.28.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jax=0.3.5
  - jaxlib=0.3.2
  - jupyter_client=7.0.4
  - jupyter_core=4.8.1
  - jupyter_server=1.11.0
  - jupyterlab=3.1.14
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.8.2
  - jupyterlab_widgets=1.0.2
  - matplotlib-base=3.4.3
  - matplotlib-inline=0.1.3
  - nbclassic=0.3.2
  - nbclient=0.5.4
  - nbconvert=6.2.0
  - nbformat=5.1.3
  - notebook=6.4.4
  - numba=0.55.1
  - numpyro=0.9.1
  - pandas=1.2.5
  - pandoc=2.14.2
  - pandocfilters=1.5.0
  - patsy=0.5.2
  - pip=21.2.4
  - pynndescent=0.5.4
  - pyro-api=0.1.2
  - pyro-ppl=1.7.0
  - pytables=3.6.1
  - python=3.8.12
  - python-annoy=1.17.0
  - pytorch=1.10.2
  - pytorch-lightning=1.5.10
  - r-base=4.1.3
  - r-igraph=1.3.0
  - r-leiden=0.3.9
  - r-matrix=1.4_1
  - r-matrixstats=0.61.0
  - r-reticulate=1.24
  - r-rtsne=0.15
  - r-sctransform=0.3.3
  - r-seurat=4.1.0
  - r-seuratobject=4.1.0
  - r-uwot=0.1.11
  - scanpy=1.8.1
  - scikit-learn=1.0
  - scipy=1.7.1
  - scvi-tools=0.16.2
  - seaborn=0.11.2
  - seaborn-base=0.11.2
  - session-info=1.0.0
  - statsmodels=0.12.2
  - umap-learn=0.5.1
  - pip:
    - anndata2ri==1.0.6
    - h5py==2.10.0
    - igraph==0.9.8
    - louvain==0.7.0
    - numpy==1.18.1
    - python-igraph==0.9.8
    - rpy2==3.4.2
    - scib==1.0.2
