name: bp-integration
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - absl-py=0.14.0
  - aiohttp=3.7.4.post0
  - alabaster=0.7.12
  - anndata=0.7.6
  - anyio=3.3.2
  - appnope=0.1.2
  - argon2-cffi=20.1.0
  - async-timeout=3.0.1
  - async_generator=1.10
  - attrs=21.2.0
  - babel=2.9.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bbknn=1.5.1
  - bleach=4.1.0
  - blinker=1.4
  - blosc=1.21.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.2
  - ca-certificates=2021.5.30
  - cachecontrol=0.12.6
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=4.2.2
  - cachy=0.3.0
  - certifi=2021.5.30
  - cffi=1.14.4
  - chardet=4.0.0
  - charset-normalizer=2.0.0
  - cleo=0.7.6
  - click=8.0.1
  - clikit=0.4.3
  - colorama=0.4.4
  - commonmark=0.9.1
  - cryptography=3.4.7
  - cycler=0.10.0
  - dataclasses=0.8
  - debugpy=1.4.1
  - decorator=4.4.2
  - defusedxml=0.7.1
  - docutils=0.17.1
  - dunamai=1.6.0
  - entrypoints=0.3
  - et_xmlfile=1.0.1
  - freetype=2.10.4
  - fsspec=2021.9.0
  - future=0.18.2
  - get_version=3.5
  - google-auth=1.35.0
  - google-auth-oauthlib=0.4.6
  - grpcio=1.38.1
  - h5py=3.4.0
  - hdf5=1.12.1
  - html5lib=1.1
  - idna=3.1
  - imagesize=1.2.0
  - importlib-metadata=4.8.1
  - importlib_metadata=4.8.1
  - ipykernel=6.4.1
  - ipython=7.28.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jbig=2.1
  - jedi=0.18.0
  - jinja2=3.0.1
  - joblib=1.0.1
  - jpeg=9d
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter_client=7.0.4
  - jupyter_core=4.8.1
  - jupyter_server=1.11.0
  - jupyterlab=3.1.14
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.8.2
  - jupyterlab_widgets=1.0.2
  - keyring=18.0.1
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - lcms2=2.12
  - legacy-api-wrap=1.2
  - lerc=2.2.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.79.1
  - libcxx=12.0.1
  - libdeflate=1.7
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.2.1
  - libgfortran=5.0.0
  - libgfortran5=9.3.0
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libnghttp2=1.43.0
  - libopenblas=0.3.17
  - libpng=1.6.37
  - libprotobuf=3.16.0
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libtiff=4.3.0
  - libwebp-base=1.2.1
  - llvm-openmp=12.0.1
  - llvmlite=0.37.0
  - lockfile=0.12.2
  - lz4-c=1.9.3
  - markdown=3.3.4
  - markupsafe=2.0.1
  - matplotlib-base=3.4.3
  - matplotlib-inline=0.1.3
  - mistune=0.8.4
  - mkl=2021.3.0
  - mock=4.0.3
  - msgpack-python=1.0.2
  - multidict=5.1.0
  - natsort=7.1.1
  - nbclassic=0.3.2
  - nbclient=0.5.4
  - nbconvert=6.2.0
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - networkx=2.6.3
  - ninja=1.10.2
  - notebook=6.4.4
  - numba=0.54.0
  - numexpr=2.7.3
  - numpy=1.20.3
  - oauthlib=3.1.1
  - olefile=0.46
  - openjpeg=2.4.0
  - openpyxl=3.0.9
  - openssl=1.1.1l
  - opt_einsum=3.3.0
  - packaging=21.0
  - pandas=1.2.5
  - pandoc=2.14.2
  - pandocfilters=1.5.0
  - parso=0.8.2
  - pastel=0.2.0
  - patsy=0.5.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.3.2
  - pip=21.2.4
  - pkginfo=1.7.1
  - poetry=1.0.10
  - prometheus_client=0.11.0
  - prompt-toolkit=3.0.20
  - protobuf=3.16.0
  - ptyprocess=0.7.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.20
  - pydeprecate=0.3.0
  - pygments=2.10.0
  - pyjwt=2.1.0
  - pylev=1.3.0
  - pynndescent=0.5.4
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyro-api=0.1.2
  - pyro-ppl=1.7.0
  - pyrsistent=0.14.11
  - pysocks=1.7.1
  - pytables=3.6.1
  - python=3.8.0
  - python-annoy=1.17.0
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytorch=1.9.0
  - pytorch-lightning=1.3.8
  - pytz=2021.1
  - pyu2f=0.1.5
  - pyyaml=5.4.1
  - pyzmq=22.3.0
  - readline=8.1
  - requests=2.26.0
  - requests-oauthlib=1.3.0
  - requests-toolbelt=0.8.0
  - requests-unixsocket=0.2.0
  - rich=10.11.0
  - rsa=4.7.2
  - scanpy=1.8.1
  - scikit-learn=1.0
  - scipy=1.7.1
  - scvi-tools=0.13.0
  - seaborn=0.11.2
  - seaborn-base=0.11.2
  - send2trash=1.8.0
  - setuptools=58.0.4
  - shellingham=1.4.0
  - sinfo=0.3.1
  - six=1.16.0
  - sleef=3.5.1
  - sniffio=1.2.0
  - snowballstemmer=2.1.0
  - sphinx=4.2.0
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - sqlite=3.36.0
  - statsmodels=0.12.2
  - stdlib-list=0.7.0
  - tbb=2021.3.0
  - tensorboard=2.6.0
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.8.0
  - terminado=0.12.1
  - testpath=0.5.0
  - threadpoolctl=2.2.0
  - tk=8.6.11
  - toml=0.10.2
  - tomlkit=0.5.11
  - torchmetrics=0.5.1
  - tornado=6.1
  - tqdm=4.62.3
  - traitlets=5.1.0
  - typing-extensions=3.10.0.2
  - typing_extensions=3.10.0.2
  - umap-learn=0.5.1
  - urllib3=1.26.7
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.57.0
  - werkzeug=2.0.1
  - wheel=0.37.0
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.6.3
  - zeromq=4.3.4
  - zipp=3.5.0
  - zlib=1.2.11
  - zstd=1.5.0
  - pip:
    - session-info==1.0.0
