name: cell2loc_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python = 3.7
  - pip
  - pytest >= 6.2.2
  - numpy >= 1.18.5
  - pandas >= 1.0.4
  - jupyter >= 1.0.0
  - ipykernel >= 5.3.4
  - leidenalg >= 0.8.0
  - python-igraph >= 0.8.2
  - nose >= 1.3.7
  - scanpy >= 1.5.1
  - scipy >= 1.4.1
  - louvain >= 0.6.1
  - hyperopt >= 0.2.4
  - loompy >= 2.0.16
  - cmake >= 3.17.0
  - dill >= 0.3.1
  - ipython >= 7.15.0
  - bbknn >= 1.3.9
  - seaborn >= 0.10.1
  - matplotlib >= 3.2.1
  - request >= 2.83.1
  - cython >= 0.29.17
  - pip:
      - pyro-ppl>=1.7.0
      - scvi-tools>=0.15.3
      - torch>=1.9.0