name: extended-single-cell-tutorial
channels:
  - default
  - conda-forge
  - bioconda
dependencies:
  - scikit-learn >= 0.24
  - imbalanced-learn
  - pandas >= 1
  - matplotlib-base
  - seaborn
  - plotly
  - jupytext
  - beautifulsoup4
  - jupyter-book
  - ghp-import
  - pip
