name: book
channels:
  - defaults
  - conda-forge
dependencies:
  - conda-forge::python==3.12
  - conda-forge::jupyter-book==1.0.4.post1
  - conda-forge::jupytext==1.16.7
  - conda-forge::beautifulsoup4==4.13.3
  - conda-forge::playwright==1.50.1
  - conda-forge::sphinx==7.*
  - pip
  - pip:
      - lamindb[bionty,jupyter,zarr]
