name: lineage-tracing
channels:
  - defaults
  - conda-forge
dependencies:
  - conda-forge::python=3.9.12
  - conda-forge::scanpy=1.9.1
  - conda-forge::anndata=0.8.0
  - pip:
      - umap-learn==0.5.2
      - pandas==1.4.3
      - numpy==1.21.6
      - matplotlib==3.5.2
      - git+https://github.com/YosefLab/Cassiopeia@master#egg=cassiopeia-lineage
      - session_info
