name: interoperability
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::python=3.9.16
  - conda-forge::jupyterlab=3.6.3
  - conda-forge::scanpy=1.9.3
  - anndata2ri=1.2
  - bioconductor-basilisk=1.9.12
  - bioconductor-scuttle=1.8.0
  - bioconductor-singlecellexperiment=1.20.0
  - bioconductor-zellkonverter=1.8.0
  - ipywidgets=8.1.0
  - r-base=4.2
  - r-hdf5r=1.3.8
  - r-remotes=2.4.2
  - r-reticulate=1.30
  - r-sessioninfo=1.2.2
  - r-seurat=4.3.0
  - r-seuratobject=4.1.3
  - rpy2=3.5.11
  - session-info=1.0.0
  # Additional R packages installed manually using {remotes}
  # remotes::install_github("mojaveazure/seurat-disk@9b89970eac2a3bd770e744f63c7763419486b14c")
  # remotes::install_github("cellgeni/sceasy@v0.0.7")
