name: interoperability
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::python=3.12.9
  - conda-forge::jupyterlab=4.3.5
  - conda-forge::scanpy=1.10.4
  - anndata2ri=1.3.2
  - bioconductor-basilisk=1.14.1
  - bioconductor-mudata=1.6.0
  - bioconductor-scuttle=1.12.0
  - bioconductor-singlecellexperiment=1.24.0
  - bioconductor-zellkonverter=1.12.1
  - ipywidgets=8.1.5
  - mudata=0.3.1
  - r-base=4.3.3
  - r-hdf5r=1.3.12
  - r-remotes=2.5.0
  - r-reticulate=1.40.0
  - r-sessioninfo=1.2.3
  - r-seurat=5.2.1
  - r-seuratobject=5.0.2
  - rpy2=3.5.11
  - session-info=1.0.0
  # Additional R packages installed manually using {remotes}
  # remotes::install_github("mojaveazure/seurat-disk@9b89970eac2a3bd770e744f63c7763419486b14c")
  # remotes::install_github("cellgeni/sceasy@v0.0.7")
  # remotes::install_github("PMBio/MuDataSeurat@e34e908")
