name: deg
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8
  - scanpy=1.8.2
  - pandas=1.2.5
  - r-base=4.1
  - bioconductor-mast=1.20.0
  - bioconductor-edger=3.36.0
  - bioconductor-singlecellexperiment=1.16.0
  - r-lme4
  - notebook
  - rpy2=3.4.5
  - anndata2ri
  - pip
  - pip:
      - sc-toolbox
