name: differential-gene-expression
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::python=3.9.15
  - conda-forge::scanpy=1.9.1
  - conda-forge::r-base=4.2.2
  - bioconda::bioconductor-mast=1.24.0
  - bioconda::bioconductor-edger=3.40.0
  - bioconda::bioconductor-singlecellexperiment=1.20.0
  - conda-forge::r-lme4
  - conda-forge::jupyterlab
  - conda-forge::rpy2=3.5.6
  - bioconda::anndata2ri=1.1
  - conda-forge::pip
  - pip:
      - sc-toolbox
      - decoupler
