name: pathway
channels:
  - conda-forge
  - bioconda
  - r
dependencies:
  - conda-forge::r-base=4.1.2
  - conda-forge::python=3.8.12
  - conda-forge::pip
  - conda-forge::rpy2=3.5.1
  - conda-forge::scanpy=1.9.1
  - conda-forge::anndata=0.8.0
  - conda-forge::ipykernel
  - conda-forge::session-info
  - conda-forge::umap-learn
  - conda-forge::scikit-misc
  - bioconda::bioconductor-singlecellexperiment=1.16.0
  - bioconda::bioconductor-fgsea=1.20.0
  - bioconda::bioconductor-edger=3.36.0
  - bioconda::bioconductor-limma=3.50.1
  - bioconda::anndata2ri==1.0.6
  - conda-forge::r-ggplot2
  - conda-forge::r-statmod
  - conda-forge::cffi
  - pip:
      - decoupler
      - omnipath
