#######################################################################################
# Book settings
title : Extended single-cell tutorial
author: Theislab
logo: 'theislab_logo.png'

# Information about where the book exists on the web
description: >-
  extended single-cell tutorial
exclude_patterns:
  -  _build
  - Thumbs.db
  - .DS_Store
  - "**.ipynb_checkpoints"
  - "figures"
  - "datasets"
  - "README.md"


#######################################################################################
# Execution settings
execute:
  execute_notebooks           : "off"
  timeout                     : 6000

#######################################################################################
# Parse and render settings
parse:
  myst_enable_extensions:
    - colon_fence
    - dollarmath
    - linkify
    - substitution

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar         : false
  use_edit_page_button        : true
  use_repository_button       : true
  use_issues_button           : true
  favicon: _static/favicon.ico
  comments:
    hypothesis: true
  extra_footer: |
    <div>
      Brought to you by
      <a href="https://www.github.com/theislab">Theislab</a>,
      with many thanks to the single-cell community as a whole!
    </div>

# #######################################################################################
# Interact link settings
notebook_interface            : "notebook"

sphinx:
  config:
    nb_custom_formats:
      .py:
        - jupytext.reads
        - fmt: py:percent
    # Needed for plotly rendering:
    # https://jupyterbook.org/interactive/interactive.html#plotly
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js

#######################################################################################
# Launch button settings
repository:
  url                         : https://github.com/theislab/extended-single-cell-tutorial

binder:
  binderhub_url               : "https://mybinder.org"
  text                        : "Launch binder"

latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex
