name: paired-integration
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::python=3.9.15
  - conda-forge::scanpy=1.9.1
  - conda-forge::r-base=4.2.2
  - conda-forge::r-seurat=4.3.0
  - bioconda::bioconductor-singlecellexperiment=1.20.0
  - conda-forge::notebook
  - conda-forge::rpy2=3.5.6
  - bioconda::anndata2ri=1.1
  - conda-forge::pip
  - pip:
      - muon
      - pysam
      - mofapy2
      - scib
      - scvi-tools
      